### ISSUE TITLE
Api remains undefined for unit tested component that contains an ag-grid.

### ISSUE THREAD

**Issue by basvandenberg** [ceolter/ag-grid-angular#126]
**I'm submitting a ...**
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
For unit tests of components that contain a ag-grid component, the ag-grid api remains `undefined`.

**Expected behavior**
When running a component unit test (for a component containing an ag-grid-ng2 component), the `gridOpiotns.api` should be defined (in the `ngOnInit` function).

**Minimal reproduction of the problem with instructions**

Having a component `projects-page.ts` that works as expected, with defined `gridOptions` and `columnDefs`, and with `ngOnInit`:
```
ngOnInit() {
    this.gridOptions.api.setColumnDefs(this.columnDefs);
}
```
The `projects-page.spec.ts` contains (stripped down to contain only the relevant ag-grid things):  
```
import {By} from '@angular/platform-browser';
import {ComponentFixture, TestBed, async} from '@angular/core/testing';
import {AgGridModule} from 'ag-grid-ng2/main';
import {ProjectsPageComponent} from './projects-page.component';

describe('ProjectsPageComponent', () => {

    let fixture: ComponentFixture;

    beforeEach(async(() => {

        TestBed.configureTestingModule({
            declarations: [
                ProjectsPageComponent
            ],
            imports: [
                AgGridModule.withComponents([])
            ],
            providers: [
            ]
        });

        fixture = TestBed.createComponent(ProjectsPageComponent);
        fixture.detectChanges(); // Calls ngOnInit function, but gridOptions.api is undefined there.
    });

    it('should create projects page component', () => {
        expect(fixture.componentInstance).toBeTruthy();
    });
});
```
Then the test fails because `this.gridOptions.api` is `undefined` in the `ngOnInit` function.

**What is the motivation / use case for changing the behavior?**
Cannot run component unit tests, because of api undefined errors.

**Please tell us about your environment:**

* **ag-grid-ng2 version:** 7.2.2

* **Angular version:** 2.4.3

* **Browser:** -

* **Language:** -

**Comment by SatyabratKumarSingh** [comment]
Hi, I facing the same issue.. Can this be looked urgently?

**Comment by saranyapm** [comment]
Facing same issue..

**Comment by SatyabratKumarSingh** [comment]
Any update on this?

**Comment by aborchew** [comment]
+1

**Comment by dmngu9** [comment]
+1

**Comment by ciesielskico** [comment]
+1

**Comment by johnyesit** [comment]
+1

**Comment by dmngu9** [comment]
i got it working in AngularJs project. I had to $compile ag grid and then $digest. The ag grid API only becomes available when onGridReady method is fired

**Comment by seanlandsman** [comment]
Hi - the seed project (https://github.com/ceolter/ag-grid-angular-seed) now has examples with karma and jasmine - please have a look and see if this helps

Not that the api(s) will only be available after you run detect changes on your fixture

````
    it('grid API is not available until  `detectChanges`', () => {
        expect(gridComponent.gridOptions.api).not.toBeTruthy();
    });

    it('grid API is available after `detectChanges`', () => {
        fixture.detectChanges();
        expect(gridComponent.gridOptions.api).toBeTruthy();
    });
````

**Comment by MariuszPL55** [comment]
The link is not working and this doesn't solve my problem and have really similar, but I am initializing `gridApi` using `onGridReady` method.
