### ISSUE TITLE
Issue with infinite scroll rendering in IE11

### ISSUE THREAD

**Issue by pramodcnair** [ceolter/ag-grid-angular#133]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We are using Virtual Paging/Infinite Scrolling for ag-grid but we are getting a delay of at least 1 sec delay for rendering data for IE11.

**Expected behavior**

The scroll should be smoother for IE11. You can try your own ag-grid in IE 11, and scroll swiftly top and bottom and you can see it's differently behaving from what we have in Chrome or Firefox

**Minimal reproduction of the problem with instructions**

I am using below link to check the behavior. I tried it in IE11 and scroll down and up quickly and for a moment the whole grid goes blank in IE11 but not happens in Chrome or Firefox
https://www.ag-grid.com/javascript-grid-virtual-paging/#gsc.tab=0

**What is the motivation / use case for changing the behavior?**

The grid should behave same across all the supported browsers. 

**Please tell us about your environment:**

OS: Windows8/10

* **ag-grid-angular version:** 2.0.X

ag-grid 7.2.x
ag-grid-ng2 7.2.x

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X

Angular version 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 11.0.9600.18538
Edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0 ES5

**Comment by bahrus** [comment]
Everything about this grid is great, except for the scrolling speed, especially IE11 and Edge.  Where I work, I think we would purchase the enterprise license for sure, if we see some improvements on this.

**Comment by seanlandsman** [comment]
Hi

We've spent a lot of time around IE11 performance and I'm afraid there isn't much more we can do around this.

The best we can suggest is to use suppressScrollLag which will improve the user experience, but that's all I can suggest at this time I'm afraid

If you're an enterprise client feel free to log this in our Members Forum, but as I say I'm afraid we've probably gone as far as we can with IE11 scrolling performance.

thanks

**Comment by srishti0212** [comment]
Hi Is there any update on this issue ?

**Comment by seanlandsman** [comment]
Hi @bahrus - version 13.0.0 introduced a new renderering engine that we've found to be 6x faster for IE.

There'll be a new blog on it soon (tomorrow I think) but in the meantime the changelog details some of the changes

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0

Specifically: "New rendering engine - now the grid works blazing fast, even on IE9 and IE10! Our tests show the grid work 6 times faster. One better browsers (Chrome etc) you will notice the scrolling much smoother."

**Comment by seanlandsman** [comment]
@srishti0212 the above might be of interest to you too

**Comment by bahrus** [comment]
That's great, thanks for the update.

**Comment by srishti0212** [comment]
Thankyou for the update, could you please tell me if this version is ready for download and where could I get it from? We are evaluating AG-grid and this feature will help us make the decision sooner.

**Comment by seanlandsman** [comment]
@bahrus the block is here, if you're interested: https://www.ag-grid.com/ag-grid-8-performance-hacks-for-javascript/

@srishti0212 yes, its available - please see ag-grid.com (under the getting started section) for how to access ag-grid, depending on your framework/build tool. 

It is available via github & npm
