### ISSUE TITLE
onNewRowsLoaded of custom filter (IFilterAngularComp) not working

### ISSUE THREAD

**Issue by felixpis** [ceolter/ag-grid-angular#135]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Added new custom filter for angular2 ag-grid component (ColDef.filterFramework).
Implemented all the needed methods of IFilterAngularComp (agInit, isFilterActive, doesFilterPass, getModel, setModel, afterGuiAttached). And also added method onNewRowsLoaded. But after reload row data this method not performed

**Expected behavior**

Method onNewRowsLoaded should be performed on every row data change

**Please tell us about your environment:**

* **ag-grid-angular version:** 8.1.0

* **ag-Grid version:** 8.1.1

* **Angular version:** 2.4.1

* **Browser:** [all]

* **Language:** [TypeScript 2.0]

**Comment by seanlandsman** [comment]
Hi

This has been fixed and will be in the next release, which will be later today

thanks
