### ISSUE TITLE
Error on grid load: No provider for BaseComponentFactory

### ISSUE THREAD

**Issue by yonatannn** [ceolter/ag-grid-angular#136]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When running ng2 page with aggrid, I receive the following JS error:
**Error: Uncaught (in promise): Error: Error in ./RichGridDeclarativeComponent class RichGridDeclarativeComponent - inline template:42:8 caused by: No provider for BaseComponentFactory!**

Full stacktrace appear below
**Expected behavior**

**Minimal reproduction of the problem with instructions**
I just copied the ng2 example project and used few of the compoents from that project. I noted this issue happen other people, see here:
https://blog.knoldus.com/2016/10/12/implementing-ag-grid-in-angular-2/

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, VSCode, npm 3.3, ng 2.4.7, webpack 2

* **ag-grid-angular version:** 2.0.X

8.1

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

8.1

* **Angular version:** 2.0.X

2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by seanlandsman** [comment]
You need to import the AgGridModule as follows:

    AgGridModule.withComponents(
        [..optional components...]
    )

The docs around angular with ag-grid can be found here: https://www.ag-grid.com/javascript-grid-getting-started/?framework=angular
