### ISSUE TITLE
Export Framework Component Wrapper in main.ts

### ISSUE THREAD

**Issue by jedancona** [ceolter/ag-grid-angular#137]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ng2FrameworkComponentWrapper is not exported in main.

**Expected behavior**
ng2FrameworkComponentWrapper to be exported

**Comment by seanlandsman** [comment]
Can I ask why you need this exported? Is it affecting your build?

**Comment by jedancona** [comment]
We need it exported because we have a use case where we are need to extend the angular wrapper.

**Comment by seanlandsman** [comment]
Hi @jedancona 

Was good to meet you guys at ngconf - I've just made this change, it should be built & exported in our next release

thanks
