### ISSUE TITLE
how to disable chcekbox for some rows condition wise

### ISSUE THREAD

**Issue by Ankitpatwa92** [ceolter/ag-grid-angular#138]
I want to show disabled check box selection for some rows condition wise.
Is there any way i can make check box disable??

**Comment by seanlandsman** [comment]
Hi

Please post support questions either on our free forum ( https://ag-grid.com/forum/forumdisplay.php?fid=4 ) or on stackoverflow

Github is reserved for bugs or feature requests

thanks
