### ISSUE TITLE
Ag grid size in production

### ISSUE THREAD

**Issue by nicolae536** [ceolter/ag-grid-angular#140]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Is there any way to optimize ag-grid size ? Tree shaking or any other import structe.
![image](https://cloud.githubusercontent.com/assets/9453094/25066295/b48f1cce-222a-11e7-9242-d3debd513d8d.png)
I is quite big and I would like to optimize it a little bit.

**Expected behavior**

The library should be much smaller.

**Minimal reproduction of the problem with instructions**

Build an application with ag-grid inside it, I usw webpack.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 9.0.1

* **Angular version:** 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I'm afraid that the size of the library is unlikely to change in the short to medium term. 

We might look at modularizing the library at some point, but as I say this won't be in the near future

**Comment by dev-fullstacktechnology** [comment]
Then what about build strategy of the project using ag-grid. my project takes more than 20 seconds due to only size issue of ag-grid library. The build generates size of 3MB file for ag-grid library.

**Comment by nicolae536** [comment]
do you build your project using webpack?

**Comment by nicolae536** [comment]
if you use webpack for development you could use dll bundles plugin and build ag grid ag grid as a dll

**Comment by kalpesh-b** [comment]
@nicolae536 do you have any sample code, how to build ag-grid as a dll?
