### ISSUE TITLE
How to show dynamic values in ag-grid cell editor select

### ISSUE THREAD

**Issue by SatyabratKumarSingh** [ceolter/ag-grid-angular#141]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I want to show dynamic drop down options for each row of ag-grid.

Suppose for each row, department might be different and based on that I plan to filter list of subjects (available option for users to select in dropdown)

Here is my code:

        this.gridOptions.columnDefs = {
            headerName: 'Department',
            field: 'financingCurrency',
            editable: false,                            
            suppressSorting: false,
            cellClass: 'grid-align'
        },

        {
            headerName: 'Subject',
            field: 'subject',
            editable: true,
            cellEditor: 'select',
            filter: 'text',
            cellEditorParams: {
                values: this.subjects;                    
            },
            suppressSorting: false,
            cellClass: 'grid-align'
        }
  }
I am using free version of ag-grid with Angular 2.

Does someone have any idea about it?

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Please dont raise support requests here.

See https://www.ag-grid.com/example-angular/?framework=angular#gsc.tab=0 for examples on using angular and ag-grid
