### ISSUE TITLE
Multiple ag-gid-angular with angular2 component(one component) not working as expected

### ISSUE THREAD

**Issue by sanjeev2315** [ceolter/ag-grid-angular#142]
I am using angular2 and i have 3 grids in one component. 1 grid is on the main screen which works fine and 2 other grids in one modal and in 2 different tabs. So initially when i load my app, i can see the main grid loaded correctly, and on clicking a button on same grid, i can see both grids in modal are loaded with correct data. Till this point things are working fine. But once i navigate to other screens of app which had different component and then comes back to home screen thereafter main grid works fine but the grid in modal doesnt rendered. Surprisingly modal is allocated the size of the grid but no grid is rendered(no headers, no data). If i refresh the page it works fine till i stay on the same screen.

Doubts:- Is ag-grid-angular(8.2.0) is compatible for using multiple grids in same component or am i missing something else here.
Please respond as i am in very urgent need to fix this.

**Comment by seanlandsman** [comment]
Please follow the issue template - provide a plunker or similar and we can investigate further
