### ISSUE TITLE
What i should to use instead cellEditorFramework?

### ISSUE THREAD

**Issue by renolmachado** [ceolter/ag-grid-angular#144]
I get the following message: "ng2FrameworkFactory.js:37 colDef.cellEditorFramework.component is deprecated - please refer to https://ag-grid.com/best-angular-2-data-grid/"

I use cellEditorFramework in the columns definition: _cellEditorFramework: { component: DecimalCellEditorComponent, moduleImports: [CommonModule, FormsModule] }_

Dependencies: 
    "ag-grid": "7.x",
    "ag-grid-ng2": "7.x",

**Comment by seanlandsman** [comment]
Hi

Please take a look at the documentation here: https://ag-grid.com/ag-grid-next-steps/?framework=angular

thanks
