### ISSUE TITLE
column menu filter is not showing in Chrome but in IE, it is shown. (If iam applying custom date filter)

### ISSUE THREAD

**Issue by rajgopalk** [ceolter/ag-grid-angular#145]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Iam applying date filter with datepicker option. it is working fine in IE browser. Not in Chrome, entire filter column is not showing in chrome.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

As per the issue template please dont post support queries here. Either use our free forum or stackoverflow for this
