### ISSUE TITLE
Custom event shows: "ag-Grid-ng2: could not find EventEmitter"

### ISSUE THREAD

**Issue by louwie17** [ceolter/ag-grid-angular#147]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When triggering a custom event like grid.api.dispatchEvent('rollback'), which is not part of the default ag-grid list we get this console.log: 'ag-Grid-ng2: could not find EventEmitter: rollback'

**Expected behavior**
Since ag-grid seems to allow for custom event triggers it should either not give the console warning or allow us to turn it off. As the custom event gets triggered correctly when passed into the grid options.

**Minimal reproduction of the problem with instructions**
Sample of bug: http://plnkr.co/edit/R1ibW6ovRvtzylIUzcCK?p=preview, when 'Click me' is clicked it both calls the callback in the gridOptions and shows: 'ag-Grid-ng2: could not find EventEmitter: rollback'

**What is the motivation / use case for changing the behavior?**
Using custom events without having logs appear.

**Please tell us about your environment:**

* **ag-grid-angular version:** 9.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 9.0.X

* **Angular version:** 4.0.X hybrid with angular js

* **Browser:** [all]

* **Language:** [all]

**Comment by seanlandsman** [comment]
Hi

dispatchEvent is designed to be used to trigger grid events, not arbitrary ones - as such we only look for and use events we recognise.

It is not designed to be used with app specific events
