### ISSUE TITLE
ag-grid-angular is not being published on bower?

### ISSUE THREAD

**Issue by RusinovAnton** [ceolter/ag-grid-angular#148]
```
[x] feature request
```

➜ bower install --save ag-grid-angular bower  
ENOTFOUND Package ag-grid-angular not found

**Comment by seanlandsman** [comment]
Hi

I'm afraid as angular is not available in bower neither is ag-grid-angular - this old but still relevant answer may be of help here: https://www.quora.com/Why-is-Angular-2-not-available-in-Bower
