### ISSUE TITLE
Custom Scrollbar not working with grid

### ISSUE THREAD

**Issue by deephakdd** [ceolter/ag-grid-angular#149]
I am trying to use custom scrollbar malihu-scrollbar with the grid .
but its not working .
any ideas on how to get a customscrolbar for grid .

Any help appreciated 

thanks in advance

**Comment by seanlandsman** [comment]
As per the issue template please don't use GitHub for support queries. Either use our Members Forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or use StackOverflow
