### ISSUE TITLE
Disable Sorting for few columns

### ISSUE THREAD

**Issue by deephakdd** [ceolter/ag-grid-angular#150]
Hi,
How can we disable sorting for few Columns ,

I do not want sorting to be done for a column of icons are images .

how can that be done?

for angular 1 we had something like surpressSort = true;

how can we do that in ag-grid-angular ?

Any help appreciated

**Comment by seanlandsman** [comment]
As per the issue template please don't use GitHub for support queries. Either use our Members Forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) or use StackOverflow

You can suppress per column with the suppressSorting property
