### ISSUE TITLE
Passing arguments to an angular4 editor for ag-grid

### ISSUE THREAD

**Issue by st-clair-clarke** [ceolter/ag-grid-angular#154]
I have been studying the examples at [https://www.ag-grid.com/example-angular-third-party/#ng2bootstrap&gsc.tab=0](https://www.ag-grid.com/example-angular-third-party/#ng2bootstrap&gsc.tab=0). Given the specific md-select.component.ts example, is there a way for me to pass into the editor the fruits array?

In otherwords, given the column definition below, how can I pass-in an array parameter into the SelectEditorComponent
```
    this.columnDefs = [
      {
        headerName: 'Stopped', field: 'stopped', width: 200, editable: true,
        cellEditorFramework: SelectEditorComponent
      }
    ]
```

I am asking because this would prevent me from creating different individual editor for the different select components.

Cheers

**Comment by cosmo777** [comment]
this.columnDefs = [
      {
        headerName: 'Stopped', field: 'stopped', width: 200, editable: true,
        cellEditorFramework: SelectEditorComponent,
        cellEditorParams: {
                    array: {data...}
                }
      }
    ]

then in your agInit of your component
agInit(params: any): void {
var data = params.array;
}

**Comment by st-clair-clarke** [comment]
Thanks.

**Comment by seanlandsman** [comment]
I assume @st-clair-clarke answer has helped, so closing - let me know if still an issue
