### ISSUE TITLE
ag-grid-angular --paginationEvents and custom pagination is not available

### ISSUE THREAD

**Issue by Bhawna14** [ceolter/ag-grid-angular#156]
Hi @ceolter ,

As per my requirement, i need pagination where total page no, next,last, previous buttons would listen to my service call and show data based on that.
Only event mentioned on tutorial 'paginationChanged' throws error when i declare it as this.gridOptions.paginationChanged= userPagination;

Is there any way by which i can define that on clicking 'NEXT' on the pannel , i can make server call to get more data??

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. 

Use either stackoverflow or our members forum ( https://ag-grid.com/forum/forumdisplay.php?fid=5 )  for support queries

**Comment by Bhawna14** [comment]
Thats the link for enterprise user.. i am not using enterprise verson
