### ISSUE TITLE
GroupCellRenderer has no properties in common with ...

### ISSUE THREAD

**Issue by bputt** [ceolter/ag-grid-angular#158]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When compiling typescript using webpack, I get the error:
```
ERROR in [at-loader] ./node_modules/ag-grid/dist/lib/rendering/cellRenderers/groupCellRenderer.d.ts:17:22

TS2559: Type 'GroupCellRenderer' has no properties in common with type 'ICellRenderer'.
```

**Expected behavior**

I'd expect it to compile w/out error

**Minimal reproduction of the problem with instructions**
None at this time

**What is the motivation / use case for changing the behavior?**
I was using version 9 and just tried using 11

**Please tell us about your environment:**
CentOS 7

* **ag-grid-angular version:** 2.0.X
11.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
N/A

* **Angular version:** 2.0.X
4.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A as this occurs during build

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.4.1

**Comment by bputt** [comment]
related to: https://github.com/ceolter/ag-grid/issues/1708 and rolled back to typescript 2.3.4 and this error doesn't occur

**Comment by seanlandsman** [comment]
Hi,

Yes, related to TS 2.4 - we'll see what we can do about this our side but for now rolling back in your only option around this

thanks
