### ISSUE TITLE
Responsive grid

### ISSUE THREAD

**Issue by lazysatyr25** [ceolter/ag-grid-angular#159]
Hi! I need responsive grid like in this component [https://rawgit.com/jefersonestevo/angular-smd/master/dist/index.html#/angular-smd/demo-datatable](url) . Can i change grid template on window resize?  Thanks.

**Comment by seanlandsman** [comment]
Please see the documentation here on options around resizing: https://www.ag-grid.com/javascript-grid-responsiveness/
