### ISSUE TITLE
Missing cacheBlockSize Input

### ISSUE THREAD

**Issue by Wykks** [ceolter/ag-grid-angular#160]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

Since version 10.0.x infiniteBlockSize is now called cacheBlockSize

* **ag-grid-angular version:** 11.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 11.0.0

**Comment by seanlandsman** [comment]
Hi,

This has been fixed and will be available in our next release
