### ISSUE TITLE
Select control in the cellEditorFramework not selected the row value

### ISSUE THREAD

**Issue by Bhimisetty** [ceolter/ag-grid-angular#162]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Select in the CellEditorFramework is not selected the param value. 

**Expected behavior**
 Select in the CellEditorFramework should selected the param value.

**Minimal reproduction of the problem with instructions**

```
@Component({
    selector: 'child-cell',
    template: `<div fxLayout="row" class="grid-actions">
          <select (change)="invokeParentMethod($event)" [value]="selectedValue">
            <option *ngFor="let reference of references" [value]="reference.domaiN_DETAIL_ID">{{reference.domaiN_DETAIL_DESC}}</option>
        </select>
        </div>`
})
export class GridSelectComponent implements ICellRendererAngularComp, OnInit {
    public params: any;
    public references: any;
    public selectedValue: any;

    agInit(params: any): void {
        this.params = params;
        this.selectedValue = params.value;
    }

    public invokeParentMethod($event: MouseEvent, mode: string) {
        $event.preventDefault();
        this.params.context.componentParent.select(this.params, $event);
    }

    constructor(private domainService: DomainService) {

    }

    ngOnInit(): void {
        this.domainService.getStatuses("Status").subscribe(response => this.references = response);
    }
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 11.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 11.0.0

* **Angular version:** 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi,

I'm afraid I'm not sure what this.params.context.componentParent.select(this.params, $event); is supposed to do.

This sounds like a good candidate for our members forum - https://ag-grid.com/forum/forumdisplay.php?fid=5

Can you please post an entry there and we can try resolve this problem for you

thanks

**Comment by Bhimisetty** [comment]
Hi,
Thank you for reply. I got solved the issue myself only.  And regarding the code "this.params.context.componentParent.select(this.params, $event)" will call the parent component "select" method when we changed the dropdown value.
