### ISSUE TITLE
Uncaught TypeError: Cannot read property 'GridOptionsWrapper' of undefined(…)

### ISSUE THREAD

**Issue by kkjallepalli** [ceolter/ag-grid-angular#163]
Hi, I am using angular hybrid application (contains Angular 1 and Angular 2) upgrade module approach and i used AoT with roll-up in my application. Currently, we are using UI grid (Angular 1.x) in our project and now i am replacing the UI grid with ag-grid-angular (11.x.x).
 
I was imported ag-grid and ag-grid-angular as dependencies in package json file .Just i was included the AgGridModule in root module imports and roll-up config file as well in named exports .Now i am getting Cannot read property 'GridOptionsWrapper' of undefined(…). 

I was tried with the same in quick-start example AoT with roll-up , it is working fine and grid was loaded.

Is the ag-grid-angular will supports AoT with roll-up or the problem with hybrid approach?

**Comment by seanlandsman** [comment]
I'm afraid we don't currently support rollup with our angular project - this is something we're looking to add support for soon, but at this time rollup won't work with ag-grid-angular
