### ISSUE TITLE
Rename repo into ag-grid-ng

### ISSUE THREAD

**Issue by DzmitryShylovich** [ceolter/ag-grid-angular#64]
Angular 3 is coming in ~6 months. https://angularjs.blogspot.com.by/2016/10/versioning-and-releasing-angular.html

**Comment by seanlandsman** [comment]
this is a good point - we'll have a discussion but you're probably right, keeping it ng2 probably isnt appropriate in the longer term

thanks!

**Comment by ceolter** [comment]
spoken to Sean offline about this - think it's best we keep ng2 until they make they make the first move to ng3 - as if we call it ng, then it's going to confuse angular 1 people

**Comment by seanlandsman** [comment]
Hi @DzmitryShylovich 

As I know you use the grid with AOT, the new 7.x beta  supports both AOT and JIT mode: https://www.ag-grid.com/angular-2-beta-release/

Its a breaking change release though, so maybe worth checking out to see if you hit any issues when using it

thanks

**Comment by seanlandsman** [comment]
This has now been done
