### ISSUE TITLE
Ag-Grid doesn't work inside an editor of another Ag-Grid.

### ISSUE THREAD

**Issue by Anruin** [ceolter/ag-grid-angular#75]
Greetings.
We are trying to use AgGrid in template of the editor of root AgGrid. We are using dynamic building of the editor component to be able to show different renderers/editors for different AgGrid rows. But it doesn't compile and Angular says that it can't bind to AgGridNG2 properties, errors are like the following one:

```
core.umd.js:3462 EXCEPTION: Template parse errors:
Can't bind to 'gridOptions' since it isn't a known property of 'ag-grid-ng2'.
1. If 'ag-grid-ng2' is an Angular component and it has 'gridOptions' input, then verify that it is part of this module.
2. If 'ag-grid-ng2' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
                         id="products_grid"
                         class="ag-architect"
                         [ERROR ->][gridOptions]="grid_options"
                         [columnDefs]="column_defs"
                         [rowData]="row_data"
"): BindParameterProductEditorComponent@19:7
```

Is there any workaround for this problem? AgGrid is very cool and flexible, so it could be great to use it even inside its own editor. :)

Please let me know if I can provide any additional information on the issue.

Thanks.

**Comment by Anruin** [comment]
Please let me know if I can provide any additional information on the issue.

**Comment by Anruin** [comment]
@seanlandsman we use it within an editor inside another grid. Like, editor should render another grid from which we have to choose some items. And that editor is dynamically created for the grid row cell.

**Comment by seanlandsman** [comment]
hi @Anruin - an interesting use case here, not one we've seen before. I'll take a look and see what I can find, but this will likely only be next week now I'm afraid.

I'll see if I can come up with a working plunker of a grid within a grid for you, and if not see what the issues are

**Comment by seanlandsman** [comment]
Hi @Anruin - I can take a look at this with any luck next week. Do you have an example plunker or repo I can use for investigation of your setup?

**Comment by Anruin** [comment]
Hi, I'm closing the issue as with current version everything works nicely :+1:  Thanks!
